services:
  # Database
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pitchforge-network

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:4000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - pitchforge-network

  # Local ML Service
  pitch-ml-service:
    build:
      context: ./pitch-ml-service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEV_MODE=true
      - SERVICE_NAME=Pitch ML Service
      - API_V1_STR=/api/v1
      - PYTHONPATH=/app
      - MODEL_CACHE_DIR=/app/models
    volumes:
      - ./pitch-ml-service:/app
      - ml_models:/app/models
    networks:
      - pitchforge-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pitchforge-network

volumes:
  postgres_data:
  ml_models:

networks:
  pitchforge-network:
    driver: bridge